### ISSUE TITLE
 Authenticate w/ tokens w/ the HTCondor-CE collector

### ISSUE THREAD

**Issue by ddbox** [glideinWMS/glideinwms#105]
This is redmine issue https://cdcvs.fnal.gov/redmine/issues/26576
OSG issues https://opensciencegrid.atlassian.net/browse/HTCONDOR-735
and   https://opensciencegrid.atlassian.net/browse/HTCONDOR-991

**Comment by mambelli** [comment]
In GWMS 3.9.5 and 3.7.7
