### ISSUE TITLE
continue with submission if token_util claims SciToken is expired.

### ISSUE THREAD

**Issue by ddbox** [glideinWMS/glideinwms#142]
A request from the operators is to continue submission if the attached SciToken is expired, a held condor submission is easier to debug that sleuthing through the logs as is required with current behavior.

This behavior made it in to the 3.7 series but not the 3.9 series, it needs to go into the next release candidate.

Expanding this ticket to 'make sure the behavior is the same for both branches as far as stripping newlines and continuing if token is expired'

**Comment by BrunoCoimbra** [comment]
This behavior was added to 3.9 with PR #145.
