### ISSUE TITLE
Requesting less glideins when using multiple credentials

### ISSUE THREAD

**Issue by mambelli** [glideinWMS/glideinwms#171]
**Describe the bug**
When using multiple credentials or tokens+GSI the Frontend is requesting fewer Glideins (Idle and Max) than it should.
There are 2 underlying problems:
- the splitting expression in the plug-ins is using regular division where it should use integer division
- GSI is added to tokens submission to support legacy systems, it should not be counted as an additional credential to split glideins

**To Reproduce**
Configure a frontend to use SciToken and also send a GSI proxy (current default)

**Expected behavior**
Both issues should be fixed:
- integer division should be in the expression to provide the same results as in python2
- the x509 proxy added to scitokens to support legacy Gratia probes should not be counted when partitioning glideins to credentials

**Screenshots**
NA

**Desktop (please complete the following information):**

-   GlideinWMS version: 3.9.5 (and earlier 3.9.x)
-   Python version: 3.6
-   OS version: rhel7
-   HTCondor version: 9.0.11 (any)

**Additional context**
NA

**Comment by BrunoCoimbra** [comment]
This was addressed with PR #178.
