### ISSUE TITLE
Missing startup_dir results in glidein_startup.sh file leak

### ISSUE THREAD

**Issue by brianhlin** [glideinWMS/glideinwms#189]
In [glidien_cleanup](https://github.com/glideinWMS/glideinwms/blob/master/creation/web_base/glidein_startup.sh#L405-L427) (sic), cleanup gets skipped if the glidein can't `cd` into the `startup_dir`. This logic was added in a big refactor commit https://github.com/glideinWMS/glideinwms/commit/79cb6ff2360fd15ed580329cd4ddf5ec680a2cb7 but there doesn't seem to be any indication of why it was added.

An [HTCondor bug](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1223) appears to result in the CE removing the `startup_dir` shortly after the job gets the SIGTERM so we end up leaking user job sandboxes.

We think that the glidein should continue with cleanup, even if the `startup_dir` doesn't exist

**Comment by JaimeFrey** [comment]
I agree this is a bad behavior on HTCondor's part. It affects Hosted-CE configurations (i.e. bosco-style ssh access to the site), and doesn't affect installs where the CE is on the site submit point.

**Comment by mambelli** [comment]
Fixed in PR. As I mentioned in the PR info and Glidein exit status will be completely lost after cleanup because the start dir is no more available and cleanup will remove the rest. But I guess it is the lesser evil.
