### ISSUE TITLE
setup_x509.sh creates proxy file in directory used for tokens

### ISSUE THREAD

**Issue by matyasselmeci** [glideinWMS/glideinwms#201]
**Describe the bug**
`setup_x509.sh` creates a file called `ticket/myproxy` from the `X509_USER_PROXY`.  This is the same directory as used for IDTOKENS.  This causes the `condor_startd` to complain that it cannot parse the proxy file as a JWT.  Due to a separate HTCondor issue (https://opensciencegrid.atlassian.net/browse/HTCONDOR-1271), this fills up the StartdLog with noise.

**To Reproduce**
Submit a job through the OSG frontend, examine the StartdLog for "Failed to decode jwt in keyfile" messages.

**Comment by mambelli** [comment]
Fixed by #198
