### ISSUE TITLE
setup_x509.sh fails to copy gsi proxy to glidein in hybrid mode

### ISSUE THREAD

**Issue by ddbox** [glideinWMS/glideinwms#220]
**Describe the bug**
glideins in release candiates for 3.9.6 <= rc4 fail to copy X509_USER_PROXY to correct directory glide_XXXXX/cred.d/(proxy_name)

**To Reproduce**
send a pilot proxy and idtoken via 3.9.6.rc4 or rc.3 

**suggested fix**
function get_x509_proxy in setup_x509.sh: replace -n test (true if not null) with -z test (true if null)
get_x509_proxy() {
     local cert_fname=${1:-"$X509_USER_PROXY"}
-    if [[ -n "$cert_fname" || ! -e "$cert_fname" ]]; then
+    if [[ -z "$cert_fname" || ! -e "$cert_fname" ]]; then
         echo "Proxy certificate '$cert_fname' does not exist."
         return 1
     fi

**Comment by mambelli** [comment]
Fixed in updated PR for 3.9.6 rc5
