### ISSUE TITLE
Factory Knob to Control Rebuilding of cvmfsexec Distributions

### ISSUE THREAD

**Issue by namrathaurs** [glideinWMS/glideinwms#262]
**Is your feature request related to a problem? Please describe.**
Reconfiguring factories is taking too long, anywhere between 30-60 minutes, to complete the rebuilding of cvmfsexec distributions. This was reported by Jeff Dost during January 2023's stakeholders' meeting.

**Describe the solution you'd like**
Add a formal knob/trigger in the factory that would provide more control, i.e. disable/enable as needed, over the rebuilding of cvmfsexec distributions. This is useful for scenarios when the cvmfs is to be provisioned on demand for a specific entry (as opposed to all the entries defined in the configuration file of the factory).

**Describe alternatives you've considered**
Remove the script, specified as a pre-reconfig hook, that builds these cvmfsexec distributions.

**Info (please complete the following information):**

-   Priority: High
-   Stakeholder: FactoryOps
-   Component: Factory

**Additional context**
The latest version of the reconfig hook rebuilds the cvmfsexec distributions only when a new version of cvmfsexec package is available OR when factory reconfig/upgrade is initiated the very first time. Otherwise, the rebuilding of distributions is ignored and existing versions of the distributions, that are available on the factory, are shipped to the entries/CEs by the glidein(s).

**Comment by mambelli** [comment]
As a workaround, the build may be disabled by moving `create_cvmfsexec_distros.sh` out of the `/etc/gwms-factory/hooks.reconfig.pre` directory
