### ISSUE TITLE
Advertise the HTCondor attributes in the glidefactory ClassAds

### ISSUE THREAD

**Issue by mambelli** [glideinWMS/glideinwms#307]
**Is your feature request related to a problem? Please describe.**
Advertise the HTCondor attributes in the glidefactory ClassAds.

Hammercloud and other CMS tools need to know which queue the Glideins are submitted to.
The glidefactory ClassAds have information about each entry.
Queue information used to be in the RSL string or the gatekeeper string which are both advertised in the ClassAd. 
With new HTCondor protocols (HTCondor-CE, ARC REST interface, ...) the queue information is now in the condor submit attributes `<config><submit><submit_attrs>...` which are not included in the ClassAd. So the queue information is lost/not available outside the XML configuration.

**Describe the solution you'd like**
We'd like to see advertised the queue information, e.g. the condor submit attributes

**Describe alternatives you've considered**
Does not matter where the queue information is advertised 

**Info (please complete the following information):**

-   Priority: high
-   Stakeholders: CMS
-   Components: factory

**Additional context**
Request raised in discussion w/ S.Lammel
https://ggus.eu/index.php?mode=ticket_info&ticket_id=162296

**Comment by mmascher** [comment]
Since we are at it, we should probably add all the submit attributes. I was looking for xcount for the work I am doing about efficiency

**Comment by stlammel** [comment]
Any update on this? We really need to get the queue information back into the CMS VO-feed.
Thanks,
 - Stephan

**Comment by stlammel** [comment]
Any update Marco? @mambelli  This is becoming urgent for CMS now.
 - Stephan

**Comment by stlammel** [comment]
ping

**Comment by stlammel** [comment]
Any update?   - Stephan

**Comment by mambelli** [comment]
Fixed by PR #382
