### ISSUE TITLE
jquery loading blocked

### ISSUE THREAD

**Issue by bbockelm** [glideinWMS/glideinwms#34]
I noticed that the latest version of Chrome blocks the loading of jquery in the frontend's web interface.  This is because it is linked over `http://` even when `https://` is used to to load the page.  Here's an example link:

```
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
```

Can we always load this resource over HTTPS?

**Comment by mambelli** [comment]
I created a Redmine ticket, https://cdcvs.fnal.gov/redmine/issues/25283
Changes have been merged and will be in the next release.
I'm using links without protocol (href="//ajax.googleapis.com/ajax/), so it will work w/ the protocol of the page
