### ISSUE TITLE
Permit IDTOKENS when querying schedds

### ISSUE THREAD

**Issue by bbockelm** [glideinWMS/glideinwms#35]
We are working on removing GSI auth from some of our schedds and would like to use IDTOKENS instead.

Unfortunately, it seems that there are various places where GSI is hardcoded when we are talking to the schedd:

- `condorSecurity.py`
- `cvWCreate.py`

Can we always allow authentication with `IDTOKENS` and `SCITOKENS`?

**Comment by ddbox** [comment]
This is also tracked in redmine issue https://cdcvs.fnal.gov/redmine/issues/25299

**Comment by ddbox** [comment]
This is resolved with the release of 3.7.3, closing ticket.
