### ISSUE TITLE
01_gwms_metrics.config comments cause condor_gangliad to crash

### ISSUE THREAD

**Issue by timtheisen** [glideinWMS/glideinwms#368]
**Describe the bug**
The copyright comments in 01_gwms_metrics.config are not in ClassAd format. When the condor_gangliad attempts to load the classads, it errors out and the condor_master tries to restart it to no avail.

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots and/or console outputs to help explain your problem.

**Info (please complete the following information):**
Stakeholders and components can be a comma separated list or on multiple lines.
If you add a new stakeholder or component, not on the sample list, add it on a line by its own.

-   GlideinWMS version:
-   Python version:
-   OS version:
-   HTCondor version:
-   Priority: Priority level of this bug [critical, high, medium, low]
-   Stakeholders: Concerned stakeholder(s) [CMS, FactoryOps, Fermilab, FIFE, HEPCloud, IGWN, OSG]
-   Components: The affected component due to this bug [frontend, factory, glidein, documentation, CI, testing, release, factory monitoring, frontend monitoring, ...]

**Additional context**
Add any other context or supporting files about the problem here.

**Comment by mambelli** [comment]
@timtheisen Is it there a way to add a comment in a ClassAd format file?
