### ISSUE TITLE
Hosted CE module loading / singularity detection weirdness

### ISSUE THREAD

**Issue by mambelli** [glideinWMS/glideinwms#395]
**Describe the bug**
A hosted CE is failing to detect apptainer.
From the detailed logs
[job.3610066.0.err.txt](https://github.com/glideinWMS/glideinwms/files/14091133/job.3610066.0.err.txt)
[job.3610066.0.out.txt](https://github.com/glideinWMS/glideinwms/files/14091134/job.3610066.0.out.txt)
, apptainer runs correctly (EC 0), but fails the validation of the output.
Possible causes are:
- Apptainer/Singularity test fails when /proc file system is not available in the image
- The format of /proc is different in the image used for the test

There could also be a problem with the image or Apptainer execution
This behavior requires further investigation

**To Reproduce**
Apptainer is in tmp/glide_Pb9H5L/main/singularity_setup.sh invoked w/ the command:
```
"/cm/local/apps/apptainer/current/bin/singularity" -vvv -d  exec --home "/tmp/glide_Pb9H5L":/srv --pwd /srv  --ipc --contain  --pid --bind "/etc/hosts,/etc/localtime"  "/tmp/glide_Pb9H5L/images/htc__rocky__9.sif" cat /proc/self/uid_map
```
And the result is:
```
INFO  Singularity at '/cm/local/apps/apptainer/current/bin/apptainer' failed (ec:0) w/ unexpected output
```

**Expected behavior**
It is unexpected to have EC 0 and not the correct output

**Screenshots**

**Info (please complete the following information):**

-   GlideinWMS version: 3.10.5
-   Python version:
-   OS version:
-   HTCondor version:
-   Priority:  high
-   Stakeholders: FactoryOps, OSG
-   Components: glidein

**Additional context**

**Comment by mambelli** [comment]
To patch a 3.10.5 or 3.10.6 Factory, replace the content of `/var/lib/gwms-factory/web-base/singularity_lib.sh` with https://raw.githubusercontent.com/mambelli/glideinwms/v310/i395_apptainer_test/creation/web_base/singularity_lib.sh and run a Factory upgrade.
This will allow to use apptainer/singularity as long as it returns exit code 0 and provides further output for troubleshooting.

**Comment by mambelli** [comment]
I started PR #396 to work on the Issue. I'd like some further troubleshooting before merging a final solution, but the current content (patch above) will get you going.

**Comment by mambelli** [comment]
I updated PR #396 to fix the Issue. It was not considering the case when uid_map had no initial blank. The link above points to the updated solution, with fixed validation and failure of the test when the output is wrong. You can use it for patching until the next release.

**Comment by mmascher** [comment]
Not re-opening this just yet, but a T0 operator reported an issues with "paused jobs":

![image](https://github.com/glideinWMS/glideinwms/assets/1586246/4130af7a-8b90-4fd2-b1a6-7a81a04fb258)

This are the job logfiles: http://mmascher.web.cern.ch/mmascher/Job_1080.tar.bz2

I will investigate more tomorrow morning

**Comment by LinaresToine** [comment]
Thank you @mmascher

**Comment by mmascher** [comment]
FYI: After some investigation the issue with the T0 jobs does not seem related to this patch
