### ISSUE TITLE
Error in cvmfsexec_platform_select.sh failing at setup

### ISSUE THREAD

**Issue by mambelli** [glideinWMS/glideinwms#429]
**Describe the bug**
Glideins are failing in the version currently in the master branch because `cvmfsexec_platform_select.sh` is failing (exiting w/ non 0 exit code) during initial validation of custom scripts.

In stderr you can see:
```
cvmfs_helper_funcs.o831bk.sh: OK
Signature OK for main:cvmfs_helper_funcs.o831bk.sh.
ce-workspace 08-03-2024 01:16:54 UTC     WARNING: Validating CVMFS with oasis.opensciencegrid.org: directory empty or does not have .cvmfsdirtab
ce-workspace 08-03-2024 01:16:54 UTC     INFO: CVMFS locally installed: no
ce-workspace 08-03-2024 01:16:54 UTC     INFO: Unprivileged user namespaces supported and enabled
=== validation OK in /var/lib/condor/execute/dir_14001/glide_ruvzLi/main/cvmfs_helper_funcs.sh (0) ===
cvmfsexec_platform_select.o831bk.sh: OK
Signature OK for main:cvmfsexec_platform_select.o831bk.sh.
=== Validation error in /var/lib/condor/execute/dir_14001/glide_ruvzLi/main/cvmfsexec_platform_select.sh ===
Sat Aug  3 01:16:54 UTC 2024 Error running '/var/lib/condor/execute/dir_14001/glide_ruvzLi/main/cvmfsexec_platform_select.sh'
    Invalid command line argument: Must be one of {osg, egi, default}
Sat Aug  3 01:16:55 UTC 2024 Sleeping 320
```
And in stdout:
```
JOB_SCRATCH_LIMIT_BYTES = "Unknown"
Executing (flags:) /var/lib/condor/execute/dir_14001/glide_ruvzLi/main/cvmfs_helper_funcs.sh
Executing (flags:) /var/lib/condor/execute/dir_14001/glide_ruvzLi/main/cvmfsexec_platform_select.sh
Invalid command line argument: Must be one of {osg, egi, default}
```

**To Reproduce**
Run the workspaces (latest version) linked to master from GitHub

**Expected behavior**
Successful run-test.sh

**Screenshots**
NA

**Info (please complete the following information):**
Stakeholders and components can be a comma-separated list or on multiple lines.
If you add a new stakeholder or component, not on the sample list, add it on a line by its own.

-   GlideinWMS version: master
-   Python version: 3.9
-   OS version: Alma9
-   HTCondor version: Any
-   Priority: critical
-   Stakeholders: Fermilab
-   Components: glidein

**Additional context**
No release possible until this is fixed

**Comment by namrathaurs** [comment]
@mambelli was the factory knob `CVMFS_SRC` defined in the factory configuration file?
```
<attr name="CVMFS_SRC" const="True" glidein_publish="False" job_publish="True" parameter="True" publish="True" type="string" value="osg"/>
```

**Comment by namrathaurs** [comment]
My previous comment was irrelevant to what the actual problem was. Regardless of whether `CVMFS_SRC` was used or not, the execution of `cvmfsexec_platform_select.sh` should not occur if on-demand CVMFS will not be used (absence of `GLIDEIN_USE_CVMFSEXEC` attribute in factory config) or if it has not been requested by the user/job (`GLIDEIN_USE_CVMFSEXEC` set to `0` in factory config).

Marco clarified that the glidein setup that failed did not want to use the on-demand CVMFS provisioning, which basically meant that it was a vanilla factory configuration.
