### ISSUE TITLE
gwms-renew-proxies service should check if local VOMS cert is expired

### ISSUE THREAD

**Issue by brianhlin** [glideinWMS/glideinwms#45]
When using the `gwms-renew-proxies` service, we've noticed that `voms-proxy-fake`/`voms-proxy-direct` will happily sign a proxy's VOMS AC even though the VOMS cert is expired. In these instances, the `gwms-renew-proxies` service should check whether or not the VOMS cert is > start time and < end time before calling `voms-proxy-fake` and fail if the VOMS cert is no longer valid.

**Comment by mambelli** [comment]
@brianhlin Is this still relevant given the current x509 support? Will there be someone form the OSG team that can update the script?
