### ISSUE TITLE
Overhaul the token creation process

### ISSUE THREAD

**Issue by bbockelm** [glideinWMS/glideinwms#49]
The token creation process in 3.7 has a few holes.

1.  The TRUST_DOMAIN (e.g., issuer) must be set to match that on the collector.  Right now, it's set to the frontend hostname; should take TRUST_DOMAIN from the condor config.
2. The authorizations are much too permissive.  We should reduce this to `READ`, `ADVERTISE_STARTD`, and `ADVERTISE_MASTER`.
3.  It sets up a separate password per GLIDEIN Site.  This must be synchronized with the collector, which is hard to do if the number of sites is fluctuating.
4. A better way to approach this is to use a dedicated key (which only has to synchronize once) and generate a different identity per site.  This keeps the ability to do a per-site revocation but reduces the operational complexity.
5. The lifetime is much too short.  It's set to 2 hours -- this needs to be set to the maximum queue time of the pilot.  It's not clear how long this should be (I arbitrarily used 1 day but might need to be longer).

I copy below a script below I use for the CHTC frontend that we use for the 3.9 branch.

```
KEY=glidein-cm.chtc.wisc.edu

ID=$1

# create a key for creating the token if needed

AUTH='-authz READ -authz ADVERTISE_STARTD -authz ADVERTISE_MASTER'

export _condor_SEC_PASSWORD_DIRECTORY=/etc/condor/passwords.d-gwms/
export _condor_TRUST_DOMAIN=cm.chtc.wisc.edu

# create the token, echo it to stdout
/usr/bin/condor_token_create  -lifetime 86400 -key ${KEY} ${AUTH} -identity "gwms-${ID}@chtc.wisc.edu"
```

**Comment by ddbox** [comment]
issues 2 and 5 were addressed in release 3.7.4.  The remaining are addressed in redmine issue #25817
