### ISSUE TITLE
glidein_cleanup doesn't clean up files chmodded read-only

### ISSUE THREAD

**Issue by matyasselmeci** [glideinWMS/glideinwms#56]
We've been experimenting with having expanded Singularity images inside the work dir; these have many directories that are read-only by the owner (e.g. have 0555 or 0500 permissions). `rm -fR` won't work to delete these because you can't delete files in a read-only directory (unless you are root). This prevents cleanup from working.

`glidein_cleanup()` should first do a `chmod -R u+w` on the directory trees it wants to delete before doing `rm -fR`. (`find $dir -type d -exec chmod ...` might be faster if there are a lot of small files in the directory tree.)

**Comment by mambelli** [comment]
Thanks. Fixes are in branch `v37/26282`.
