### ISSUE TITLE
Singularity wrapped payloads get passed unusable TMPDIR/TEMPDIR

### ISSUE THREAD

**Issue by hufnagel** [glideinWMS/glideinwms#61]
The pilot sets TMPDIR/TEMPDIR to it's own working directory within the environment it's running in. When payloads get wrapped by singularity, that path is not necessarily valid within the singularity container.

The gWMS singularity wrapper code should make sure that TMPDIR/TEMPDIR are accessible, since there could be code in the payload that just blindly tries to use TMPDIR/TEMPDIR without actually checking that it's a valid path. Either redefine it based on the bind mount rules or, maybe easier, just do an additional bind mount for it.

This is not hypothetical, CMS was running into this issue recently (with generator code) and it caused quite a bit of pain.

**Comment by mambelli** [comment]
TMP, TEMP, and TMPDIR were already unset before starting the user job. I added also TEMPDIR to the list to unset.
Should GWMS also change the bind mounts to make sure there is a temporary directory or can this ticket be closed?
