### ISSUE TITLE
Improve SHARED_PORT defaults

### ISSUE THREAD

**Issue by bbockelm** [glideinWMS/glideinwms#65]
The default shared port configuration makes the firewall configuration unnecessarily complex.

- The collector should be moved behind the shared port (as has been default since 8.4).
- Change the shared port TCP port to 9618, the IANA-reserved port for HTCondor.

This drops the firewall requirements from both 9618 and 9615 to the developer-suggested 9618-only.  The shared_port has been battle tested at quite large scales -- better to have things simpler out-of-the-box.

**Comment by ddbox** [comment]
created branch 65_improve_shared_port_defaults and requested review from marco

**Comment by ddbox** [comment]
branch merged, closing issue
