### ISSUE TITLE
OS detection broken for CentOS Stream 8

### ISSUE THREAD

**Issue by brianhlin** [glideinWMS/glideinwms#97]
For CentOS Stream 8, `/etc/redhat-release` contains:

```
[moate@fiu-svc-1 ~]$ cat /etc/redhat-release 
CentOS Stream release 8
```

Which breaks the grep here: https://github.com/glideinWMS/glideinwms/blob/bef79262b4d32586dd65aa36b6187291e2bbba46/creation/web_base/condor_platform_select.sh#L45.

We should consider parsing `/etc/os-release` instead: https://github.com/htcondor/htcondor/blob/7ecce4e5c16072162903844eef817b11c6e9b960/src/condor_scripts/condor_remote_cluster#L284-L310

**Comment by mmascher** [comment]
Fix in https://github.com/glideinWMS/glideinwms/pull/98
